### ISSUE TITLE
Create a checksum system to check if packages have changed

### ISSUE THREAD

**Issue by Hogfeldt** [Hogfeldt/bioconda_recipe_gen_ci#5]
When we download and try to build packages to decide rather the package can be use as a test for bioconda-recipe-gen, it could be nice if we only look at packages that have changed since last time.
This could probably be achieved by making an md5 checksum on all folders in bioconda-recipe/recipes or maybe we can use git to find the differences from the last time we ran a test.

**Comment by JesperBrink** [comment]
Closed with the implementation of PackageDB.
